### PR TITLE
upgrade to nrepl 0.6.0 and whidbey 2.0.0

### PR DESCRIPTION
**Pull request by johannesloetzsch**
* merged [`origin/master (v0.5.4)`](https://github.com/venantius/ultra/commit/846477e52a772c49236e772ec8c5ca590daa1f29) with [`origin/upgrade-nrepl`](https://github.com/venantius/ultra/commit/cfd4cf4245b4438c4aff3a09bd9d9128f923e652)
* upgrade to `nrepl 0.6.0` and `whidbey 2.0.0`
(https://github.com/venantius/ultra/commit/2f09643a451cb453848d4c6081709847423b1cba)
* solved https://github.com/venantius/ultra/issues/95#issuecomment-461631375
* cleanup `src/ultra/repl/whidbey.clj` by using `whidbey.plugin/repl-pprint` instead

### CODE REVIEW

**Comment by venantius** [comment]
I think this may need to be rebased onto master?

**Comment by johannesloetzsch** [comment]
> I think this may need to be rebased onto master?

I merged `upgrade-nrepl` into `master` before I did the changes. The branch of the pull request is now 2 commits ahead of master, so I think no rebase is needed.

If you are willing to use this as the new master, feel free to **squash** the changes.

**Comment by johannesloetzsch** [comment]
This branch works well with the new released `[mvxcvi/whidbey "2.1.0"]`.

I would appreciate, if you could test it, give feedback and eventually (squash+)merge it.

**Comment by venantius** [comment]
Hey - I'm sorry for the delay in getting back to you on this. 

Thank you for the work you've put in here - I've noticed you also helping out other people upstream. I've been working on this problem in a branch of my own and will be merging that. At the moment I've got everything in a workable state but the perfectionist in me is a little irked about the one remaining change in behavior that I don't love, which is [this](https://github.com/greglook/whidbey/issues/30). 

I'm going to push my changes up for now and merge into master, but I'm going to wait a few days to cut a release to see if the newline issue gets resolved before then.

**Comment by johannesloetzsch** [comment]
ok, thanks :)

**Pull request closed without merging**
