### PR TITLE
Ultra 0.6.0

### LINKED ISSUE #89: Is clojure 1.9 supported yet?
Is clojure 1.9 supported yet?
Thanks!!

And thanks for this plugin!

### LINKED ISSUE #95: Update org.clojure/tools.nrepl 0.2.12 to nrepl 0.5.3?
According to https://github.com/clojure/tools.nrepl, the active development of nREPL has moved to https://github.com/nrepl/nrepl earlier in 2018.

### LINKED ISSUE #97: Declare middleware
I'm getting these annoying warnings from Lein 2.8.2:

    Warning: implicit middleware found: ultra.plugin/middleware 
    Please declare all middleware in :middleware as implicit loading is deprecated.
    [WARNING] No nREPL middleware descriptor in metadata of #'clojure.tools.nrepl.middleware.render-values/render-values, see nrepl.middleware/set-descriptor!

This seems relevant:
https://github.com/technomancy/leiningen/blob/1dc131128279ef50f21d4d643c4d5c2133c1370d/doc/PLUGINS.md#project-middleware

### LINKED ISSUE #103: compatibility with leiningen 2.9.0
Using ultra(0.5.4) in combination with the  leiningen version 2.9.0, I get the following exception:

```
    Caused by: java.lang.RuntimeException: Unable to resolve var: clojure.instant/thread-local-utc-date-format in this context
    ....
    fipp.visit$eval3333$loading__6706__auto____3334.invoke (visit.cljc:1)
    fipp.visit$eval3333.invokeStatic (visit.cljc:1)
    fipp.visit$eval3333.invoke (visit.cljc:1)
    ...
    puget.printer$eval2467$loading__6706__auto____2468.invoke (printer.clj:1)
    ...
    whidbey.repl$eval2418$loading__6706__auto____2419.invoke (repl.clj:1)
    .....
    ultra.colorscheme$eval1974$loading__6706__auto____1975.invoke (colorscheme.clj:1)
```

apparently fipp doesn't work well with the new leningen version. Do you have any idea to fix it? Thank you

### PR DESCRIPTION
**Pull request by venantius**
Resolves #89 
Resolves #95 
Resolves #97 
Resolves #103

### CODE REVIEW

**Comment by venantius** [comment]
Resolves #103

**Comment by venantius** [comment]
Also resolves #97

**Comment by ryanmjacobs** [comment]
Hi, I apologize if this question is naive, but how can I instruct `lein` to run my local dev copy of this branch? I was able to clone and build `ultra-0.6.0-SNAPSHOT.jar`, I just need to reference it in the `.lein/profiles...` config somehow, right?

I understand that this branch may not be fully complete because of the newline issue, but I would still like to use it.

**Comment by venantius** [comment]
Hey @ryanmjacobs - if you download this branch and run `lein install`, you should be able to use `[venantius/ultra "0.6.0-SNAPSHOT"]` in your `:plugins` key per usual.

**Comment by ryanmjacobs** [comment]
Nevermind, I see that you've recently pushed `0.6.0` to `master`. I'm running that and it works great :+1:

**Pull request merged**
