### PR TITLE
Remove logic expression hints to avoid double execution

### PR DESCRIPTION
**Pull request by timothypratley**

### CODE REVIEW

**Comment by timothypratley** [comment]
Relates to issue #83

**Comment by venantius** [comment]
I have mixed feelings about dead code. My preference would be that we either pull everything and you keep working on it in a branch or we leave it as is and patch it directly.

**Comment by timothypratley** [comment]
Agreed, either is fine by me! :)

**Comment by venantius** [comment]
It's at least partly up to you - depends on how much availability you have to work on this. If you think we can get a fix mergable in the next two months, I'm happy to wait. If you don't think you'll be able to then we should pull all logic-related code (you can always re-introduce it by just running git-revert and dealing with any merge conflicts). Either way I don't think we should have half-measures where we disable the code but leave it in place.

**Comment by timothypratley** [comment]
I gave this a shot on the weekend and failed;
So I've updated the pull request to completely remove the code as requested.


The challenge is:
Given a form:   `(or :a (and :b :c (not :d) nil :f))`
Produce:
```
  (let [a# :a
           b# (if a# :not-evaluated :b)
           c# (if a# :not-evaluated (if b# :c :not-evaluated))
           d# (if a# :not-evaluated (if (and c# (not= :not-evaluated c#)) :d :not-evaluated))
           e# (if a# :not-evaluated (if (and d# (not= :not-evaluated d#)) nil :not-evaluated))
           f# (if a# :not-evaluated (if (and e# (not= :not-evaluated e#)) :f :not-evaluated))

           result# (or a# (and b# c# (not d#) e# f#))
           hint# (list 'or a# (and b# c# (not d#) e# f#))]
         <attach result# and hint# to the test result>
       )
```
But I'm failing to write the translation to produce the let binding.

**Comment by venantius** [comment]
Not to worry. We can always revisit in the future if we want.

**Pull request merged**
